# Generated by Django 4.0.4 on 2022-07-15 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0009_auto_20220708_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger_Sundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintain_balance_bill_by_bill', models.CharField(blank=True, default='Null', max_length=225)),
                ('default_credit_period', models.CharField(blank=True, default='Null', max_length=225)),
                ('check_for_credit_days', models.CharField(blank=True, default='Null', max_length=225)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.ledger')),
            ],
        ),
    ]
