# Generated by Django 4.0.4 on 2022-07-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0010_ledger_sundry'),
    ]

    operations = [
        migrations.CreateModel(
            name='receiptdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(max_length=225)),
                ('dispatch_Doc_No', models.CharField(max_length=225)),
                ('dispatch_through', models.CharField(max_length=225)),
                ('destination', models.CharField(max_length=225)),
                ('carrier_name', models.CharField(max_length=225)),
                ('bill_of_lading_no', models.CharField(max_length=225)),
                ('date', models.DateField()),
                ('motorvehicle_no', models.CharField(max_length=225)),
                ('original_invoice_no', models.CharField(max_length=225)),
                ('invoice_date', models.DateField()),
            ],
        ),
    ]
