# Generated by Django 4.0.4 on 2022-07-18 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0011_receiptdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptdetails',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.ledger'),
        ),
    ]
