# Generated by Django 4.0.4 on 2022-08-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0014_creditenote'),
    ]

    operations = [
        migrations.CreateModel(
            name='debitnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('particulars', models.CharField(max_length=255)),
                ('vouchertype', models.CharField(max_length=255)),
                ('voucherno', models.IntegerField()),
                ('debitamount', models.IntegerField()),
                ('creditamount', models.IntegerField()),
            ],
        ),
    ]
