# Generated by Django 4.0.4 on 2022-08-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0015_debitnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('under', models.CharField(max_length=255)),
                ('units', models.CharField(max_length=255)),
            ],
        ),
    ]
