# Generated by Django 4.0.4 on 2022-08-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0016_stockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('formal_name', models.CharField(max_length=255)),
                ('unitquantity_code', models.CharField(max_length=255)),
                ('no_of_decimalplaces', models.IntegerField()),
            ],
        ),
    ]
