# Generated by Django 4.0.4 on 2022-08-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0017_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditenote',
            name='debitamount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='creditamount',
            field=models.IntegerField(null=True),
        ),
    ]
