# Generated by Django 4.0.4 on 2022-08-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0018_alter_creditenote_debitamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='partydetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('mailing_address', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
