# Generated by Django 4.0.4 on 2022-08-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0019_partydetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='partydetails',
            new_name='party_details',
        ),
    ]
