# Generated by Django 4.0.4 on 2022-08-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0020_rename_partydetails_party_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditenote',
            name='id',
        ),
        migrations.AlterField(
            model_name='creditenote',
            name='voucherno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
