# Generated by Django 4.0.4 on 2022-08-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0021_remove_creditenote_id_alter_creditenote_voucherno'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditenotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('particulars', models.CharField(max_length=255)),
                ('vouchertype', models.CharField(max_length=255)),
                ('voucherno', models.IntegerField()),
                ('debitamount', models.IntegerField(null=True)),
                ('creditamount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='creditenote',
        ),
    ]
