# Generated by Django 4.0.4 on 2022-08-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0022_creditenotes_delete_creditenote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='creditenotes',
            new_name='creditenote',
        ),
    ]
