# Generated by Django 4.0.5 on 2022-09-12 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_countrymodel_groupanalysismodel_groupcreatemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_simple',
            name='comp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
            preserve_default=False,
        ),
    ]
