# Generated by Django 4.0.5 on 2022-09-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_unit_simple_comp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit_simple',
            name='comp',
        ),
    ]
